# Generated by Django 3.0.5 on 2020-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Titolo')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Introduzione')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Immagine')),
                ('tag', models.CharField(blank=True, max_length=250, null=True, verbose_name='Parole Chiave')),
                ('active', models.BooleanField(default=True, verbose_name='Pubblicato')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Post - Blog - News',
                'ordering': ['title'],
            },
        ),
    ]
